#include "persistence/FileExporter.h"
#include <fstream>
#include <sstream>
#include <iomanip>
#include <ctime>
#include <stdexcept>
#include <filesystem>

FileExporter::FileExporter() : outputDirectory("output") {}

FileExporter::FileExporter(const std::string& outputDir)
    : outputDirectory(outputDir) {}

std::string FileExporter::generateFilename(const std::string& prefix,
                                            const std::string& extension) const {
    // Create a filename with timestamp so each export is unique
    // Format: prefix_YYYYMMDD_HHMMSS.ext
    std::time_t now = std::time(nullptr);
    std::tm* lt = std::localtime(&now);

    std::ostringstream oss;
    oss << outputDirectory << "/"
        << prefix << "_"
        << std::setfill('0')
        << (lt->tm_year + 1900)
        << std::setw(2) << (lt->tm_mon + 1)
        << std::setw(2) << lt->tm_mday << "_"
        << std::setw(2) << lt->tm_hour
        << std::setw(2) << lt->tm_min
        << std::setw(2) << lt->tm_sec
        << "." << extension;

    return oss.str();
}

void FileExporter::ensureDirectoryExists() const {
    // Use C++17 filesystem to create the output directory if it doesn't exist.
    // This prevents file write failures on first run.
    try {
        std::filesystem::create_directories(outputDirectory);
    } catch (const std::filesystem::filesystem_error& e) {
        throw std::runtime_error(
            "FileExporter: cannot create output directory — " +
            std::string(e.what()));
    }
}

std::string FileExporter::exportSummaryTxt(const RouteResult& result,
                                            const WasteSystem& system) {
    ensureDirectoryExists();
    std::string filename = generateFilename("summary", "txt");

    std::ofstream file(filename);
    if (!file.is_open()) {
        throw std::runtime_error("FileExporter: cannot open file " + filename);
    }

    file << "============================================\n";
    file << "  Smart Waste Clearance — Route Summary\n";
    file << "  EcoRoute Solutions Sdn Bhd\n";
    file << "============================================\n\n";

    file << "Day: " << system.getDayNumber() << "\n";
    file << "Seed: " << system.getCurrentSeed() << "\n";
    file << "Collection Threshold: " << system.getCollectionThreshold() << "%\n\n";

    file << "Algorithm: " << result.algorithmName << "\n";
    file << "--------------------------------------------\n";

    file << std::fixed << std::setprecision(2);
    file << "Total Distance:    " << result.totalDistance << " km\n";
    file << "Travel Time:       " << result.travelTime << " hours\n";
    file << "Fuel Cost:         RM " << result.fuelCost << "\n";
    file << "Driver Wage:       RM " << result.wageCost << "\n";
    file << "Total Cost:        RM " << result.totalCost << "\n";
    file << "Waste Collected:   " << result.wasteCollected << " kg\n";
    file << "Compute Time:      " << result.runtimeMs << " ms\n\n";

    file << "Route Order:\n";
    for (int i = 0; i < static_cast<int>(result.visitOrder.size()); i++) {
        int nodeId = result.visitOrder[i];
        int idx = system.getGraph().findNodeIndex(nodeId);
        if (idx >= 0) {
            const WasteNode& node = system.getGraph().getNode(idx);
            file << "  " << (i + 1) << ". " << node.getName();
            if (!node.getIsHQ()) {
                file << " (" << node.getWasteLevel() << "%)";
            }
            file << "\n";
        }
    }

    file << "\n============================================\n";
    file << "  Generated by Smart Waste Clearance System\n";
    file << "============================================\n";

    file.close();
    return filename;
}

std::string FileExporter::exportComparisonCsv(const std::vector<RouteResult>& results,
                                               const WasteSystem& system) {
    ensureDirectoryExists();
    std::string filename = generateFilename("comparison", "csv");

    std::ofstream file(filename);
    if (!file.is_open()) {
        throw std::runtime_error("FileExporter: cannot open file " + filename);
    }

    // CSV header
    file << "Algorithm,Distance (km),Travel Time (h),Fuel Cost (RM),"
         << "Wage Cost (RM),Total Cost (RM),Waste Collected (kg),"
         << "Runtime (ms)\n";

    file << std::fixed << std::setprecision(2);

    for (const auto& r : results) {
        file << r.algorithmName << ","
             << r.totalDistance << ","
             << r.travelTime << ","
             << r.fuelCost << ","
             << r.wageCost << ","
             << r.totalCost << ","
             << r.wasteCollected << ","
             << r.runtimeMs << "\n";
    }

    // Add metadata at the bottom
    file << "\nDay," << system.getDayNumber() << "\n";
    file << "Seed," << system.getCurrentSeed() << "\n";
    file << "Threshold," << system.getCollectionThreshold() << "%\n";

    file.close();
    return filename;
}

std::string FileExporter::exportRouteDetailsTxt(const RouteResult& result,
                                                  const WasteSystem& system) {
    ensureDirectoryExists();
    std::string filename = generateFilename("route_detail", "txt");

    std::ofstream file(filename);
    if (!file.is_open()) {
        throw std::runtime_error("FileExporter: cannot open file " + filename);
    }

    file << "Route Details — " << result.algorithmName << "\n";
    file << "Day " << system.getDayNumber() << "\n\n";

    file << std::fixed << std::setprecision(2);

    // Show each leg of the route with individual segment distances
    file << "Step-by-step route:\n";
    file << "-------------------\n";

    for (int i = 0; i + 1 < static_cast<int>(result.visitOrder.size()); i++) {
        int fromId = result.visitOrder[i];
        int toId = result.visitOrder[i + 1];
        int fromIdx = system.getGraph().findNodeIndex(fromId);
        int toIdx = system.getGraph().findNodeIndex(toId);

        if (fromIdx < 0 || toIdx < 0) continue;

        const WasteNode& from = system.getGraph().getNode(fromIdx);
        const WasteNode& to = system.getGraph().getNode(toIdx);
        float segDist = system.getGraph().getDistance(fromId, toId);

        file << "  " << (i + 1) << ". "
             << from.getName() << " -> " << to.getName()
             << "  [" << segDist << " km]\n";
    }

    file << "\nTotal: " << result.totalDistance << " km\n";

    // Node waste details
    file << "\nWaste at each location:\n";
    file << "-----------------------\n";
    for (int i = 0; i < system.getGraph().getNodeCount(); i++) {
        const WasteNode& node = system.getGraph().getNode(i);
        if (node.getIsHQ()) continue;

        file << "  " << node.getName() << ": "
             << node.getWasteLevel() << "% ("
             << node.getWasteAmount() << " kg)\n";
    }

    file.close();
    return filename;
}

std::string FileExporter::getOutputDirectory() const {
    return outputDirectory;
}
