#include "persistence/FileExporter.h"

#include <ctime>
#include <filesystem>
#include <fstream>
#include <iomanip>
#include <sstream>
#include <stdexcept>

namespace {
std::tm buildLocalTimestamp(std::time_t now) {
    std::tm timestamp{};
#ifdef _WIN32
    localtime_s(&timestamp, &now);
#else
    localtime_r(&now, &timestamp);
#endif
    return timestamp;
}

std::ofstream openOutputFile(const std::string& filename) {
    std::ofstream file(filename);
    if (!file.is_open()) {
        throw std::runtime_error("FileExporter: cannot open file " + filename);
    }
    return file;
}

const WasteNode* findNodeById(const WasteSystem& system, int nodeId) {
    const int nodeIndex = system.getGraph().findNodeIndex(nodeId);
    if (nodeIndex < 0) {
        return nullptr;
    }
    return &system.getGraph().getNode(nodeIndex);
}

void writeSimulationMetadata(std::ostream& output, const WasteSystem& system) {
    output << "Day: " << system.getDayNumber() << "\n";
    output << "Seed: " << system.getCurrentSeed() << "\n";
    output << "Collection Threshold: " << system.getCollectionThreshold() << "%\n";
}
} // namespace

FileExporter::FileExporter() : outputDirectory("output") {}

FileExporter::FileExporter(const std::string& outputDir)
    : outputDirectory(outputDir) {}

std::string FileExporter::generateFilename(const std::string& prefix,
                                           const std::string& extension) const {
    const std::tm timestamp = buildLocalTimestamp(std::time(nullptr));

    std::ostringstream filename;
    filename << outputDirectory << "/"
             << prefix << "_"
             << std::setfill('0')
             << (timestamp.tm_year + 1900)
             << std::setw(2) << (timestamp.tm_mon + 1)
             << std::setw(2) << timestamp.tm_mday << "_"
             << std::setw(2) << timestamp.tm_hour
             << std::setw(2) << timestamp.tm_min
             << std::setw(2) << timestamp.tm_sec
             << "." << extension;
    return filename.str();
}

void FileExporter::ensureDirectoryExists() const {
    try {
        std::filesystem::create_directories(outputDirectory);
    } catch (const std::filesystem::filesystem_error& e) {
        throw std::runtime_error(
            "FileExporter: cannot create output directory - " +
            std::string(e.what()));
    }
}

std::string FileExporter::exportSummaryTxt(const RouteResult& result,
                                           const WasteSystem& system) {
    ensureDirectoryExists();
    const std::string filename = generateFilename("summary", "txt");
    std::ofstream file = openOutputFile(filename);

    file << "============================================\n";
    file << "  Ocean Cleanup System - Route Summary\n";
    file << "  EcoRoute Solutions\n";
    file << "============================================\n\n";

    writeSimulationMetadata(file, system);
    file << "\nAlgorithm: " << result.algorithmName << "\n";
    file << "--------------------------------------------\n";

    file << std::fixed << std::setprecision(2);
    file << "Total Distance:    " << result.totalDistance << " km\n";
    file << "Travel Time:       " << result.travelTime << " hours\n";
    file << "Fuel Cost:         RM " << result.fuelCost << "\n";
    file << "Driver Wage:       RM " << result.wageCost << "\n";
    file << "Total Cost:        RM " << result.totalCost << "\n";
    file << "Waste Collected:   " << result.wasteCollected << " kg\n";
    file << "Compute Time:      " << result.runtimeMs << " ms\n\n";

    file << "Route Order:\n";
    for (int i = 0; i < static_cast<int>(result.visitOrder.size()); ++i) {
        const WasteNode* node = findNodeById(system, result.visitOrder[i]);
        if (!node) {
            continue;
        }

        file << "  " << (i + 1) << ". " << node->getName();
        if (!node->getIsHQ()) {
            file << " (" << node->getWasteLevel() << "%)";
        }
        file << "\n";
    }

    file << "\n============================================\n";
    file << "  Generated by Ocean Cleanup System\n";
    file << "============================================\n";

    return filename;
}

std::string FileExporter::exportComparisonCsv(const std::vector<RouteResult>& results,
                                              const WasteSystem& system) {
    ensureDirectoryExists();
    const std::string filename = generateFilename("comparison", "csv");
    std::ofstream file = openOutputFile(filename);

    file << "Algorithm,Distance (km),Travel Time (h),Fuel Cost (RM),"
         << "Wage Cost (RM),Total Cost (RM),Waste Collected (kg),"
         << "Runtime (ms)\n";

    file << std::fixed << std::setprecision(2);
    for (const RouteResult& result : results) {
        file << result.algorithmName << ","
             << result.totalDistance << ","
             << result.travelTime << ","
             << result.fuelCost << ","
             << result.wageCost << ","
             << result.totalCost << ","
             << result.wasteCollected << ","
             << result.runtimeMs << "\n";
    }

    file << "\nDay," << system.getDayNumber() << "\n";
    file << "Seed," << system.getCurrentSeed() << "\n";
    file << "Threshold," << system.getCollectionThreshold() << "%\n";

    return filename;
}

std::string FileExporter::exportRouteDetailsTxt(const RouteResult& result,
                                                const WasteSystem& system) {
    ensureDirectoryExists();
    const std::string filename = generateFilename("route_detail", "txt");
    std::ofstream file = openOutputFile(filename);

    file << "Route Details - " << result.algorithmName << "\n";
    file << "Day " << system.getDayNumber() << "\n\n";
    file << std::fixed << std::setprecision(2);

    file << "Step-by-step route:\n";
    file << "-------------------\n";
    for (int i = 0; i + 1 < static_cast<int>(result.visitOrder.size()); ++i) {
        const WasteNode* fromNode = findNodeById(system, result.visitOrder[i]);
        const WasteNode* toNode = findNodeById(system, result.visitOrder[i + 1]);
        if (!fromNode || !toNode) {
            continue;
        }

        const float segmentDistance = system.getGraph().getDistance(
            fromNode->getId(), toNode->getId());
        file << "  " << (i + 1) << ". "
             << fromNode->getName() << " -> " << toNode->getName()
             << "  [" << segmentDistance << " km]\n";
    }

    file << "\nTotal: " << result.totalDistance << " km\n";
    file << "\nWaste at each location:\n";
    file << "-----------------------\n";
    for (int i = 0; i < system.getGraph().getNodeCount(); ++i) {
        const WasteNode& node = system.getGraph().getNode(i);
        if (node.getIsHQ()) {
            continue;
        }

        file << "  " << node.getName() << ": "
             << node.getWasteLevel() << "% ("
             << node.getWasteAmount() << " kg)\n";
    }

    return filename;
}

std::string FileExporter::getOutputDirectory() const {
    return outputDirectory;
}
